default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  username: root
  password: pineapple9772
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: tristo_development

test:
  <<: *default
  database: tristo_test

production:
  <<: *default
  database: <%= Rails.application.credentials.DB_NAME %>
  username: <%= Rails.application.credentials.DB_USERNAME %>
  password: <%= Rails.application.credentials.DB_PASSWORD %>
  host: <%= Rails.application.credentials.DB_HOSTNAME %>
